sudo: false

language: java

services: mongodb

node_js: "0.12"

jdk: oraclejdk8

cache:
  directories: 
          - $HOME/.m2/repository
          - ./frontend/node_modules

install:
  - npm install -g gulp-cli
  - echo "<settings><servers><server><id>bintray</id><username>\${env.BINTRAY_USER}</username><password>\${env.BINTRAY_KEY}</password></server></servers></settings>" > ~/.m2/settings.xml
  - if [[ $TRAVIS_PULL_REQUEST = false ]] && [[ $TRAVIS_BRANCH = master || $TRAVIS_BRANCH = dev-* ]] || [[ $TRAVIS_TAG = v* ]]; then export GOAL=deploy; else export GOAL=install; fi
  - if [[ $TRAVIS_TAG = v* ]]; then export ADDITIONAL_PROFILES=release; (cd backend && mvn -q -U org.seedstack:seedstack-maven-plugin:release); else export ADDITIONAL_PROFILES=snapshots; fi

script: chmod +x ./build.sh && ./build.sh

after_success: (cd backend && mvn -q coveralls:report -DrepoToken=$COVERALLS_TOKEN)
