sudo: false

language: java

services: mongodb

node_js: "0.12"

jdk: oraclejdk8

cache:
  directories: $HOME/.m2/repository

install:
  - npm install -g gulp-cli
  - echo "<settings><servers><server><id>bintray</id><username>\${env.BINTRAY_USER}</username><password>\${env.BINTRAY_KEY}</password></server></servers></settings>" > ~/.m2/settings.xml
  - if [[ $TRAVIS_TAG = v* ]]; then export ADDITIONAL_PROFILES=release; export GOAL=deploy; (cd backend && mvn -q -U org.seedstack:seedstack-maven-plugin:release); else export ADDITIONAL_PROFILES=snapshots; export GOAL=install; fi

script: chmod +x ./build.sh && ./build.sh

after_success: (cd backend && mvn -q coveralls:report -DrepoToken=$COVERALLS_TOKEN)
